[versions]
agp = "8.13.1"
androidDatabaseSqlcipher = "4.5.4"
androidxJunit = "1.3.0"
appcompatVersion = "1.7.1"
biometric = "1.2.0-alpha05"
constraintlayout = "2.2.1"
curvedbottomnavigation = "0.1.3"
espressoCoreVersion = "3.7.0"
firebaseAuth = "24.0.1"
firebaseMessaging = "25.0.1"
googleServices = "4.4.4"
hiltAndroid = "2.57.2"
itextg = "5.5.10"
junit = "4.13.2"
kotlinxCoroutinesAndroid = "1.10.2"
lifecycleViewmodel = "2.10.0"
loggingInterceptor = "5.3.2"
lottie = "6.7.1"
materialVersion = "1.13.0"
playServicesAuth = "21.4.0"
poi = "5.5.0"
retrofit = "3.0.0"
roomRuntime = "2.8.4"
securedpreferencestore = "0.7.4"
securityCryptoVersion = "1.1.0"
sqlite = "2.6.2"
toggle = "1.1.0"
work = "2.11.0"

[libraries]
android-database-sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "androidDatabaseSqlcipher" }
appcompat-v171 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
curvedbottomnavigation = { module = "com.github.qamarelsafadi:CurvedBottomNavigation", version.ref = "curvedbottomnavigation" }
espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
itextg = { module = "com.itextpdf:itextg", version.ref = "itextg" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
securedpreferencestore = { module = "online.devliving:securedpreferencestore", version.ref = "securedpreferencestore" }
security-crypto-v110alpha04 = { module = "androidx.security:security-crypto", version.ref = "securityCryptoVersion" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
toggle = { module = "com.github.angads25:toggle", version.ref = "toggle" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

